version: 2

project_name: 'kafka-pulse-go-confluentic'

builds:
  - skip: true

archives:
  - id: source-archive
    name_template: '{{ .ProjectName }}-{{ .Version }}-source'
    files:
      - go.mod
      - go.sum
      - ../../LICENSE
      - '*.go'
      - '**/*.go'
      - README.md
      - CHANGELOG.md
      # exclude test files and dist
      - '!**/*_test.go'
      - '!dist/**/*'

checksum:
  name_template: '{{ .ProjectName }}-{{ .Version }}-checksums.txt'

source:
  enabled: true
  name_template: '{{ .ProjectName }}-{{ .Version }}-full-source'

changelog:
  disable: true

release:
  github:
    owner: vmyroslav
    name: kafka-pulse-go
  
  name_template: 'Confluent Adapter v{{ .Version }}'
  
  header: |
    This release contains updates to the Confluent Kafka Go client adapter.

    ### Installation
    ```bash
    go get github.com/vmyroslav/kafka-pulse-go/adapter/confluentic@{{ .Tag }}
    ```

  footer: |
    {{ .Env.RELEASE_NOTES_CONTENT }}